# -*- coding: utf-8 -*-
"""PBLMTE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/115sz6Goansx_sE9QdqZWcCPJOEl_xqd5
"""

# Simple Image Classifiers: KNN, Logistic Regression, SVM on MNIST with Visualizations

# Step 1: Import libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, ConfusionMatrixDisplay

# Step 2: Load MNIST dataset
print("Downloading MNIST...")
X, y = fetch_openml('mnist_784', version=1, return_X_y=True, as_frame=False)
X = X / 255.0  # Normalize pixels to [0,1]
y = y.astype(int)

# Step 3: Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Standardize the data (for models that benefit from it)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 5: Visualize some sample images
def show_sample_images(X, y, num_images=9):
    plt.figure(figsize=(6, 6))
    for i in range(num_images):
        plt.subplot(3, 3, i + 1)
        plt.imshow(X[i].reshape(28, 28), cmap='gray')
        plt.title(f"Label: {y[i]}")
        plt.axis('off')
    plt.tight_layout()
    plt.show()

print("Sample images from the dataset:")
show_sample_images(X_train, y_train)

# Step 6: KNN Classifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_scaled, y_train)
knn_preds = knn.predict(X_test_scaled)
knn_acc = accuracy_score(y_test, knn_preds)
print("KNN Accuracy:", knn_acc)

# Step 7: Logistic Regression Classifier
log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train_scaled, y_train)
log_preds = log_reg.predict(X_test_scaled)
log_acc = accuracy_score(y_test, log_preds)
print("Logistic Regression Accuracy:", log_acc)

# Step 8: SVM Classifier
svm = SVC()
svm.fit(X_train_scaled, y_train)
svm_preds = svm.predict(X_test_scaled)
svm_acc = accuracy_score(y_test, svm_preds)
print("SVM Accuracy:", svm_acc)

# Step 9: Show confusion matrices
print("\nConfusion Matrix: KNN")
ConfusionMatrixDisplay.from_predictions(y_test, knn_preds)
plt.show()

print("\nConfusion Matrix: Logistic Regression")
ConfusionMatrixDisplay.from_predictions(y_test, log_preds)
plt.show()

print("\nConfusion Matrix: SVM")
ConfusionMatrixDisplay.from_predictions(y_test, svm_preds)
plt.show()

# Step 10: Compare model performance with a bar graph
models = ['KNN', 'Logistic Regression', 'SVM']
accuracies = [knn_acc, log_acc, svm_acc]

plt.figure(figsize=(8, 6))
plt.bar(models, accuracies, color=['skyblue', 'lightgreen', 'salmon'])
plt.title('Comparison of Model Accuracies (clean)')
plt.ylabel('Accuracy')
plt.ylim(0.8, 1.0)
for i, acc in enumerate(accuracies):
    plt.text(i, acc + 0.002, f"{acc:.3f}", ha='center', va='bottom')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Step 11: Simulate stronger adversarial examples by adding larger scaled noise
def add_stronger_adversarial_noise(X_scaled, epsilon=1.0):
    # sign of gaussian noise times epsilon (simple, but effective test)
    noise = epsilon * np.sign(np.random.randn(*X_scaled.shape))
    X_scaled_adv = X_scaled + noise
    return X_scaled_adv

# Create adversarial test set
X_test_adv_scaled = add_stronger_adversarial_noise(X_test_scaled, epsilon=1.0)

# Step 12: Evaluate models on adversarial examples (all models use scaled inputs for consistency)
knn_preds_adv = knn.predict(X_test_adv_scaled)
log_preds_adv = log_reg.predict(X_test_adv_scaled)
svm_preds_adv = svm.predict(X_test_adv_scaled)

knn_acc_adv = accuracy_score(y_test, knn_preds_adv)
log_acc_adv = accuracy_score(y_test, log_preds_adv)
svm_acc_adv = accuracy_score(y_test, svm_preds_adv)

print("\nKNN Accuracy (Adversarial):", knn_acc_adv)
print("Logistic Regression Accuracy (Adversarial):", log_acc_adv)
print("SVM Accuracy (Adversarial):", svm_acc_adv)

# Step 13: Plot clean vs adversarial accuracy comparison
models = ['KNN', 'LogReg', 'SVM']
clean_accs = [knn_acc, log_acc, svm_acc]
adv_accs = [knn_acc_adv, log_acc_adv, svm_acc_adv]

x = np.arange(len(models))
width = 0.35

plt.figure(figsize=(8,6))
plt.bar(x - width/2, clean_accs, width, label='Clean', color='lightblue')
plt.bar(x + width/2, adv_accs, width, label='Adversarial', color='lightcoral')
plt.ylabel('Accuracy')
plt.title('Model Accuracy: Clean vs Adversarial')
plt.xticks(x, models)
plt.ylim(0, 1)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()